import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { I18nProvider } from "next-i18next/client";
import { getResources, getT, initServerI18next } from "next-i18next/server";
import { Toaster } from "@/components/ui/sonner";
import i18nConfig from "../../i18n.config";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

initServerI18next(i18nConfig);

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const { i18n } = await getT();
  const resources = getResources(i18n);
  const lng = i18n.language;
  return (
    <html
      lang={lng}
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <I18nProvider language={lng} resources={resources}>
          <Providers>{children}</Providers>
          <Toaster richColors position="top-center" />
        </I18nProvider>
      </body>
    </html>
  );
}
