export const ErrorCode = {
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED", // 守卫缺 token / token 无效 / 过期
  COMMON_VALIDATION_FAILED: "COMMON_VALIDATION_FAILED",
  COMMON_INTERNAL_ERROR: "COMMON_INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
